### ISSUE TITLE
json text for CityI/O server need to be updated to new agreed format. 

### ISSUE THREAD

**Issue by popabczhang** [CityScope/CS_Rhino_Grasshopper_Template#1]
Update json format and inform maintainer of GAMA and Unity modules.

**Comment by agrignard** [comment]
Update JSON format according to this format https://github.com/CityScope/CS_CityIO_Backend/wiki/Data-Format

See issue https://github.com/CityScope/CS_CityIO_Backend/issues/25

**Comment by agrignard** [comment]
I think this is kind of a critical issue as it seems that aalto is now sending information with the wrong format. it can be nice if they start from the beginning to be compatible with our standard

https://cityio.media.mit.edu/api/table/cs_aalto

**Comment by popabczhang** [comment]
@agrignard, I understand. But for this time, the new format was decided after the template was shared. Next time there shouldn't be a problem. I have already informed them by email to update. Please refer to this issue: https://github.com/CityScope/CS_CityIO_Backend/issues/34

**Comment by popabczhang** [comment]
Complete: Update JSON format according to this format https://github.com/CityScope/CS_CityIO_Backend/wiki/Data-Format

Closing. 
(Alto update will be discussed on https://github.com/CityScope/CS_CityIO_Backend/issues/34 )
